---
title: "quantreg"
author: "康欣来"
date: '2023-02-09'
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(progress)
library(mgcv)
library(caret)
library(MAINT.Data)

library(iRegression)
library(MASS)
library(quantreg)
library(Rdonlp2)
library(sm)
library(Matrix)

source('IntervalPlot.R')
source('DataGeneration.R')
source("regression.R")
```

```{r}
mydata = data_generation(10, 3, c(20,20,20), c(40,40,40), c(0,0,0), c(1,1,1), -20, 20, c(0,0,0), c(0.05,0.05,0.05), 10, 20, 0)
ccrm = CM(cbind(yl, yu) ~ xl[,1] + xu[,1] + xl[,2] + xu[,2] + xl[,3] + xu[,3], data = mydata)
as.vector(ccrm$coefficients.Center) %*% c(1,1,1,1)
```

```{r include=FALSE}
t.CM = c()
t.CRM = c()
t.CCRM = c()
t.HF1 = c()
for(i in 1:100)
{
    mydata = data_generation0(1000, 3, c(20,20,20), c(40,40,40), c(0,0,0), c(1,1,1), -20, 20, c(0,0,0), c(0.05,0.05,0.05), 10, 20, i)
    t1 = Sys.time()
    cm = CM(cbind(yl, yu) ~ xl[,1] + xu[,1] + xl[,2] + xu[,2] + xl[,3] + xu[,3], data = mydata)
    t2 = Sys.time()
    t.CM = c(t.CM, t2-t1)
    
    t3 = Sys.time()
    cm = CRM(cbind(yl, yu) ~ xl[,1] + xu[,1] + xl[,2] + xu[,2] + xl[,3] + xu[,3], data = mydata)
    t4 = Sys.time()
    t.CRM = c(t.CRM, t4-t3)
    
    t5 = Sys.time()
    cm = CCRM(cbind(yl, yu) ~ xl[,1] + xu[,1] + xl[,2] + xu[,2] + xl[,3] + xu[,3], data = mydata)
    t6 = Sys.time()
    t.CCRM = c(t.CCRM, t6-t5)
    
    t7 = Sys.time()
    cm = HF1(cbind(yl, yu) ~ xl[,1] + xu[,1] + xl[,2] + xu[,2] + xl[,3] + xu[,3], data = mydata)
    t8 = Sys.time()
    t.HF1 = c(t.HF1, t8-t7)
}
```

```{r}
summary(t.CM)
summary(t.CRM)
summary(t.CCRM)
summary(t.HF1)
```

```{r}
data1c = data_generation_outlier1(20, 0, 20, 0, 1, 0, 5, 0.2, 0.5, 0, 5,seed = 0, outlierType = "central",alpha = 0.15)

plot.rect(data1c$xc, data1c$xr, data1c$yc, data1c$yr)
plot.cross(data1c$xc, data1c$xr, data1c$yc, data1c$yr)
plot.segment(data1c$xc, data1c$xr, data1c$yc, data1c$yr)
plot.dandelion(data1c$xc, data1c$xr, data1c$yc, data1c$yr)

data1r = data_generation_outlier1(20, 0, 20, 0, 1, 0, 5, 0.2, 0.5, 0, 5,seed = 0, outlierType = "range",alpha = 0.15)

plot.rect(data1r$xc, data1r$xr, data1r$yc, data1r$yr)
plot.cross(data1r$xc, data1r$xr, data1r$yc, data1r$yr)
plot.segment(data1r$xc, data1r$xr, data1r$yc, data1r$yr)
plot.dandelion(data1r$xc, data1r$xr, data1r$yc, data1r$yr)

data1cr = data_generation_outlier1(20, 0, 20, 0, 1, 0, 5, 0.2, 0.5, 0, 5,seed = 0, outlierType = "central and range",alpha = 0.15)

plot.rect(data1cr$xc, data1cr$xr, data1cr$yc, data1cr$yr)
plot.cross(data1cr$xc, data1cr$xr, data1cr$yc, data1cr$yr)
plot.segment(data1cr$xc, data1cr$xr, data1cr$yc, data1cr$yr)
plot.dandelion(data1cr$xc, data1cr$xr, data1cr$yc, data1cr$yr)
```

```{r}
data2c = data_generation_outlier2(20, 0, 20, 0, 1, 0, 5, 0.2, 0.5, 0, 5,seed = 0, outlierType = "central",alpha = 0.15)

plot.rect(data2c$xc, data2c$xr, data2c$yc, data2c$yr)
plot.cross(data2c$xc, data2c$xr, data2c$yc, data2c$yr)
plot.segment(data2c$xc, data2c$xr, data2c$yc, data2c$yr)
plot.dandelion(data2c$xc, data2c$xr, data2c$yc, data2c$yr)

data2r = data_generation_outlier2(20, 0, 20, 0, 1, 0, 5, 0.2, 0.5, 0, 5,seed = 0, outlierType = "range",alpha = 0.15)

plot.rect(data2r$xc, data2r$xr, data2r$yc, data2r$yr)
plot.cross(data2r$xc, data2r$xr, data2r$yc, data2r$yr)
plot.segment(data2r$xc, data2r$xr, data2r$yc, data2r$yr)
plot.dandelion(data2r$xc, data2r$xr, data2r$yc, data2r$yr)

data2cr = data_generation_outlier2(20, 0, 20, 0, 1, 0, 5, 0.2, 0.5, 0, 5,seed = 0, outlierType = "central and range",alpha = 0.15)

plot.rect(data2cr$xc, data2cr$xr, data2cr$yc, data2cr$yr)
plot.cross(data2cr$xc, data2cr$xr, data2cr$yc, data2cr$yr)
plot.segment(data2cr$xc, data2cr$xr, data2cr$yc, data2cr$yr)
plot.dandelion(data2cr$xc, data2cr$xr, data2cr$yc, data2cr$yr)
```

```{r}
data3c = data_generation_outlier3(20, 0, 20, 0, 1, 0, 10, 0.2, 0.5, 0, 5,seed = 0, outlierType = "central",alpha = 0.15)

plot.rect(data3c$xc, data3c$xr, data3c$yc, data3c$yr)
plot.cross(data3c$xc, data3c$xr, data3c$yc, data3c$yr)
plot.segment(data3c$xc, data3c$xr, data3c$yc, data3c$yr)
plot.dandelion(data3c$xc, data3c$xr, data3c$yc, data3c$yr)

data3r = data_generation_outlier3(20, 0, 20, 0, 1, 0, 10, 0.2, 0.5, 0, 5,seed = 0, outlierType = "range",alpha = 0.15)

plot.rect(data3r$xc, data3r$xr, data3r$yc, data3r$yr)
plot.cross(data3r$xc, data3r$xr, data3r$yc, data3r$yr)
plot.segment(data3r$xc, data3r$xr, data3r$yc, data3r$yr)
plot.dandelion(data3r$xc, data3r$xr, data3r$yc, data3r$yr)

data3cr = data_generation_outlier3(20, 0, 20, 0, 1, 0, 10, 0.2, 0.5, 0, 5,seed = 0, outlierType = "central and range",alpha = 0.15)

plot.rect(data3cr$xc, data3cr$xr, data3cr$yc, data3cr$yr)
plot.cross(data3cr$xc, data3cr$xr, data3cr$yc, data3cr$yr)
plot.segment(data3cr$xc, data3cr$xr, data3cr$yc, data3cr$yr)
plot.dandelion(data3cr$xc, data3cr$xr, data3cr$yc, data3cr$yr)
```

```{r}
data4c = data_generation_outlier4(20, 0, 20, 0, 1, 0, 10, 0.2, 0.5, 0, 5,seed = 0, outlierType = "central",alpha = 0.15)

plot.rect(data4c$xc, data4c$xr, data4c$yc, data4c$yr)
plot.cross(data4c$xc, data4c$xr, data4c$yc, data4c$yr)
plot.segment(data4c$xc, data4c$xr, data4c$yc, data4c$yr)
plot.dandelion(data4c$xc, data4c$xr, data4c$yc, data4c$yr)

data4r = data_generation_outlier4(20, 0, 20, 0, 1, 0, 10, 0.2, 0.5, 0, 5,seed = 0, outlierType = "range",alpha = 0.15)

plot.rect(data4r$xc, data4r$xr, data4r$yc, data4r$yr)
plot.cross(data4r$xc, data4r$xr, data4r$yc, data4r$yr)
plot.segment(data4r$xc, data4r$xr, data4r$yc, data4r$yr)
plot.dandelion(data4r$xc, data4r$xr, data4r$yc, data4r$yr)

data4cr = data_generation_outlier4(20, 0, 20, 0, 1, 0, 10, 0.2, 0.5, 0, 5,seed = 0, outlierType = "central and range",alpha = 0.15)

plot.rect(data4cr$xc, data4cr$xr, data4cr$yc, data4cr$yr)
plot.cross(data4cr$xc, data4cr$xr, data4cr$yc, data4cr$yr)
plot.segment(data4cr$xc, data4cr$xr, data4cr$yc, data4cr$yr)
plot.dandelion(data4cr$xc, data4cr$xr, data4cr$yc, data4cr$yr)
```

### regression comparasion
```{r}
# 存48个数据文件(rmse(4) X outlierType(4) X 3)

myprocess <- function(list_of_mat)
{
    n = length(list_of_mat)
    nr = nrow(list_of_mat[[1]])
    nc = ncol(list_of_mat[[1]]) 
    
    m = matrix(0,nrow=nr, ncol=nc)
    l95 = matrix(0,nrow=nr, ncol=nc)
    u95 = matrix(0,nrow=nr, ncol=nc)
    
    for(i in 1:nr)
    {
        for(j in 1:nc)
        {
            ele = c()
            for(s in 1:n)
            {
                ele = c(ele, list_of_mat[[s]][i,j])
            }
            m[i,j] = mean(ele)
            l95[i,j] = as.numeric(quantile(ele, 0.025))
            u95[i,j] = as.numeric(quantile(ele, 0.975))
        }
    }
    return(list(m,l95,u95))
}


simu_plotdata_save <- function(rate, n, a, b, c, d, e, f, g, h, i, j, k, l, seed, niter=200)
{
    
# ### Outlier type 1 =======================
    set.seed(0)
    n_rate = length(rate)

    print("outliertype 1:")

    data_1c_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1c_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_1r_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1r_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_1l_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1l_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_1u_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1u_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")

    data_1c_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1c_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_1r_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1r_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_1l_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1l_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_1u_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1u_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")

    data_1c_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1c_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_1r_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1r_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_1l_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1l_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_1u_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_1u_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")


    for(r in 1:length(rate))
    {
        hh = list()
        pb <- progress_bar$new(
         format = '[:bar] :percent eta: :eta',
         total = niter, clear = FALSE, width = 80
        )
        for(t in 1:niter)
        {
            pb$tick()
            data = data.frame(data_generation_outlier1(n, a, b, c, d, e, f, g, h, i, j, k, l, seed=t, outlierType="central and range", alpha=rate[r]))
            data_test = data.frame(data_generation_outlier1(floor(n*0.75), a, b, c, d, e, f, g, h, i, j, k, l, seed=t, outlierType="none"))
            # print(head(data))
            hh[[t]] = comparasion(cbind(yl,yu)~xl+xu, data[,5:8], data_test[,5:8])
        }
        hhh = myprocess(hh)
        data_1c_m[r,] = hhh[[1]][1,]
        data_1r_m[r,] = hhh[[1]][2,]
        data_1l_m[r,] = hhh[[1]][3,]
        data_1u_m[r,] = hhh[[1]][4,]

        data_1c_l[r,] = hhh[[2]][1,]
        data_1r_l[r,] = hhh[[2]][2,]
        data_1l_l[r,] = hhh[[2]][3,]
        data_1u_l[r,] = hhh[[2]][4,]

        data_1c_u[r,] = hhh[[3]][1,]
        data_1r_u[r,] = hhh[[3]][2,]
        data_1l_u[r,] = hhh[[3]][3,]
        data_1u_u[r,] = hhh[[3]][4,]
    }

    write.csv(data_1c_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1c_m.csv", row.names = FALSE)
    write.csv(data_1r_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1r_m.csv", row.names = FALSE)
    write.csv(data_1l_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1l_m.csv", row.names = FALSE)
    write.csv(data_1u_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1u_m.csv", row.names = FALSE)

    write.csv(data_1c_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1c_l.csv", row.names = FALSE)
    write.csv(data_1r_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1r_l.csv", row.names = FALSE)
    write.csv(data_1l_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1l_l.csv", row.names = FALSE)
    write.csv(data_1u_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1u_l.csv", row.names = FALSE)

    write.csv(data_1c_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1c_u.csv", row.names = FALSE)
    write.csv(data_1r_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1r_u.csv", row.names = FALSE)
    write.csv(data_1l_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1l_u.csv", row.names = FALSE)
    write.csv(data_1u_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_1u_u.csv", row.names = FALSE)

### Outlier type 2 ===================

    print("outliertype 2:")
    data_2c_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2c_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_2r_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2r_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_2l_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2l_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_2u_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2u_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")

    data_2c_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2c_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_2r_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2r_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_2l_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2l_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_2u_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2u_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")

    data_2c_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2c_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_2r_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2r_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_2l_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2l_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_2u_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_2u_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")


    for(r in 1:length(rate))
    {
        hh = list()
        pb <- progress_bar$new(
         format = '[:bar] :percent eta: :eta',
         total = niter, clear = FALSE, width = 80
        )
        for(t in 1:niter)
        {
            pb$tick()
            data = data.frame(data_generation_outlier2(n, a, b, c, d, e, f, g, h, i, j, k, l, seed=t, outlierType="central and range", alpha=rate[r]))
            hdata_test = data.frame(data_generation_outlier2(floor(n*0.75), a, b, c, d, e, f, g, h, i, j, k, l, seed=t, outlierType="none"))
            # print(head(data))
            hh[[t]] = comparasion(cbind(yl,yu)~xl+xu, data[,5:8], data_test[,5:8])
        }
        hhh = myprocess(hh)

        data_2c_m[r,] = hhh[[1]][1,]
        data_2r_m[r,] = hhh[[1]][2,]
        data_2l_m[r,] = hhh[[1]][3,]
        data_2u_m[r,] = hhh[[1]][4,]

        data_2c_l[r,] = hhh[[2]][1,]
        data_2r_l[r,] = hhh[[2]][2,]
        data_2l_l[r,] = hhh[[2]][3,]
        data_2u_l[r,] = hhh[[2]][4,]

        data_2c_u[r,] = hhh[[3]][1,]
        data_2r_u[r,] = hhh[[3]][2,]
        data_2l_u[r,] = hhh[[3]][3,]
        data_2u_u[r,] = hhh[[3]][4,]
    }

    write.csv(data_2c_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2c_m.csv", row.names = FALSE)
    write.csv(data_2r_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2r_m.csv", row.names = FALSE)
    write.csv(data_2l_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2l_m.csv", row.names = FALSE)
    write.csv(data_2u_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2u_m.csv", row.names = FALSE)

    write.csv(data_2c_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2c_l.csv", row.names = FALSE)
    write.csv(data_2r_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2r_l.csv", row.names = FALSE)
    write.csv(data_2l_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2l_l.csv", row.names = FALSE)
    write.csv(data_2u_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2u_l.csv", row.names = FALSE)

    write.csv(data_2c_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2c_u.csv", row.names = FALSE)
    write.csv(data_2r_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2r_u.csv", row.names = FALSE)
    write.csv(data_2l_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2l_u.csv", row.names = FALSE)
    write.csv(data_2u_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_2u_u.csv", row.names = FALSE)

### Outlier type 3 =======================
    print("outliertype 3:")
    data_3c_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3c_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_3r_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3r_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_3l_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3l_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_3u_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3u_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    
    data_3c_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3c_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_3r_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3r_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_3l_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3l_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_3u_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3u_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    
    data_3c_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3c_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_3r_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3r_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_3l_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3l_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_3u_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_3u_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    
    
    for(r in 1:length(rate))
    {
        hh = list()
        pb <- progress_bar$new(
         format = '[:bar] :percent eta: :eta',
         total = niter, clear = FALSE, width = 80
        )
        for(t in 1:niter)
        {
            pb$tick()
            data = data.frame(data_generation_outlier3(n, a, b, c, d, e, f, g, h, i, j, k, l, seed=t, outlierType="central and range", alpha=rate[r]))
            data_test = data.frame(data_generation_outlier3(floor(n*0.75), a, b, c, d, e, f, g, h, i, j, k, l, seed=t, outlierType="none"))
            # print(head(data))
            hh[[t]] = comparasion(cbind(yl,yu)~xl+xu, data[,5:8], data_test[,5:8])
        }
        hhh = myprocess(hh)
    
        data_3c_m[r,] = hhh[[1]][1,]
        data_3r_m[r,] = hhh[[1]][2,]
        data_3l_m[r,] = hhh[[1]][3,]
        data_3u_m[r,] = hhh[[1]][4,]
        
        data_3c_l[r,] = hhh[[2]][1,]
        data_3r_l[r,] = hhh[[2]][2,]
        data_3l_l[r,] = hhh[[2]][3,]
        data_3u_l[r,] = hhh[[2]][4,]
        
        data_3c_u[r,] = hhh[[3]][1,]
        data_3r_u[r,] = hhh[[3]][2,]
        data_3l_u[r,] = hhh[[3]][3,]
        data_3u_u[r,] = hhh[[3]][4,]
    }

    write.csv(data_3c_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3c_m.csv", row.names = FALSE)
    write.csv(data_3r_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3r_m.csv", row.names = FALSE)
    write.csv(data_3l_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3l_m.csv", row.names = FALSE)
    write.csv(data_3u_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3u_m.csv", row.names = FALSE)
    
    write.csv(data_3c_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3c_l.csv", row.names = FALSE)
    write.csv(data_3r_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3r_l.csv", row.names = FALSE)
    write.csv(data_3l_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3l_l.csv", row.names = FALSE)
    write.csv(data_3u_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3u_l.csv", row.names = FALSE)
    
    write.csv(data_3c_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3c_u.csv", row.names = FALSE)
    write.csv(data_3r_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3r_u.csv", row.names = FALSE)
    write.csv(data_3l_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3l_u.csv", row.names = FALSE)
    write.csv(data_3u_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_3u_u.csv", row.names = FALSE)

### Outlier type 4 ==========================
    print("outliertype 4:")
    data_4c_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4c_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_4r_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4r_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_4l_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4l_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_4u_m = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4u_m) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    
    data_4c_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4c_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_4r_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4r_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_4l_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4l_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_4u_l = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4u_l) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    
    data_4c_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4c_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_4r_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4r_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_4l_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4l_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    data_4u_u = as.data.frame(matrix(nrow=n_rate,ncol=12))
    names(data_4u_u) = c("CM", "CRM", "CCRM", "IRR", "FUZZY", "SSLR", "LN_IRR", "DK","HD1","HD_normal", "HD_sum","HD_modified")
    
    
    for(r in 1:length(rate))
    {
        hh = list()
        pb <- progress_bar$new(
         format = '[:bar] :percent eta: :eta',
         total = niter, clear = FALSE, width = 80
        )
        for(t in 1:niter)
        {
            pb$tick()
            data = data.frame(data_generation_outlier4(n, a, b, c, d, e, f, g, h, i, j, k, l, seed=t, outlierType="central and range", alpha=rate[r]))
            data_test = data.frame(data_generation_outlier4(floor(n*0.75), a, b, c, d, e, f, g, h, i, j, k, l, seed=t, outlierType="none"))
            # print(head(data))
            hh[[t]] = comparasion(cbind(yl,yu)~xl+xu, data[,5:8], data_test[,5:8])
        }
        hhh = myprocess(hh)
    
        data_4c_m[r,] = hhh[[1]][1,]
        data_4r_m[r,] = hhh[[1]][2,]
        data_4l_m[r,] = hhh[[1]][3,]
        data_4u_m[r,] = hhh[[1]][4,]
        
        data_4c_l[r,] = hhh[[2]][1,]
        data_4r_l[r,] = hhh[[2]][2,]
        data_4l_l[r,] = hhh[[2]][3,]
        data_4u_l[r,] = hhh[[2]][4,]
        
        data_4c_u[r,] = hhh[[3]][1,]
        data_4r_u[r,] = hhh[[3]][2,]
        data_4l_u[r,] = hhh[[3]][3,]
        data_4u_u[r,] = hhh[[3]][4,]
    }

    write.csv(data_4c_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4c_m.csv", row.names = FALSE)
    write.csv(data_4r_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4r_m.csv", row.names = FALSE)
    write.csv(data_4l_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4l_m.csv", row.names = FALSE)
    write.csv(data_4u_m,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4u_m.csv", row.names = FALSE)
    
    write.csv(data_4c_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4c_l.csv", row.names = FALSE)
    write.csv(data_4r_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4r_l.csv", row.names = FALSE)
    write.csv(data_4l_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4l_l.csv", row.names = FALSE)
    write.csv(data_4u_l,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4u_l.csv", row.names = FALSE)
    
    write.csv(data_4c_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4c_u.csv", row.names = FALSE)
    write.csv(data_4r_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4r_u.csv", row.names = FALSE)
    write.csv(data_4l_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4l_u.csv", row.names = FALSE)
    write.csv(data_4u_u,"C:\\Users\\kangxinlai\\Desktop\\zero-kp\\ZKRP\\R\\plotdata\\data_4u_u.csv", row.names = FALSE)
    
}
```

```{r}
simu_plotdata_save(rate = seq(0.01,0.2,0.03), n=200, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed = 0, niter = 100)
```
### plot of data
```{r}
data1 = data.frame(data_generation_outlier1(n=200, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType="central"))
plot.cross(data1$xc, data1$xr, data1$yc, data1$yr)

data2 = data.frame(data_generation_outlier2(n=200, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType="central"))
plot.cross(data2$xc, data2$xr, data2$yc, data2$yr)

data3 = data.frame(data_generation_outlier3(n=200, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType="central"))
plot.cross(data3$xc, data3$xr, data3$yc, data3$yr)

data4 = data.frame(data_generation_outlier4(n=200, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType="central"))
plot.cross(data4$xc, data4$xr, data4$yc, data4$yr)

data5 = data.frame(data_generation_outlier4(n=200, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType="none"))
plot.cross(data5$xc, data5$xr, data5$yc, data5$yr)

```


### rankdata
```{r warning=FALSE}
rankdata = read.csv("rankdata.csv", header = T)[,7:10]
xl_rankdata = rankdata[,1]
xu_rankdata = rankdata[,2]
yl_rankdata = rankdata[,3]
yu_rankdata = rankdata[,4]
xc_rankdata = (xu_rankdata + xl_rankdata) / 2
xr_rankdata = (xu_rankdata - xl_rankdata) / 2
yc_rankdata = (yu_rankdata + yl_rankdata) / 2
yr_rankdata = (yu_rankdata - yl_rankdata) / 2

rankdata2 = data.frame(
    yl = yl_rankdata,
    yu = yu_rankdata,
    xl = xl_rankdata,
    xu = xu_rankdata
)
plot.cross(xc_rankdata, xr_rankdata, yc_rankdata, yr_rankdata)
plot.segment(xc_rankdata, xr_rankdata, yc_rankdata, yr_rankdata)
plot.dandelion(xc_rankdata, xr_rankdata, yc_rankdata, yr_rankdata)
comparasion(cbind(yl,yu)~xl+xu, rankdata2)
```

### FlightsIdt
```{r}
library(MAINT.Data)
range_list = Ranges(FlightsIdt)/2
central_list = MidPoints(FlightsIdt)

yc = central_list$arr_delay.MidP
yr = range_list$arr_delay.LogR
yl = yc-yr
yu = yc+yr

x1c = central_list$dep_delay.MidP
x2c = central_list$air_time.MidP
x3c = central_list$distance.MidP
x1r = range_list$dep_delay.LogR
x2r = range_list$air_time.LogR
x3r = range_list$distance.LogR
x1l = x1c-x1r
x1u = x1c+x1r
x2l = x2c-x2r
x2u = x2c+x2r
x3l = x3c-x3r
x3u = x3c+x3r

dataF = data.frame(
    yl = yl,
    yu = yu,
    x1l = x1l,
    x2l = x2l,
    x3l = x3l,
    x1u = x1u,
    x2u = x2u,
    x3u = x3u
)

plot.cross(x1c, x1r, yc, yr)
plot.segment(x1c, x1r, yc, yr)
plot.dandelion(x1c, x1r, yc, yr)

plot.cross(x2c, x2r, yc, yr)
plot.segment(x2c, x2r, yc, yr)
plot.dandelion(x2c, x2r, yc, yr)

plot.cross(x1c, x1r, yc, yr)
plot.segment(x2c, x2r, yc, yr)
plot.dandelion(x2c, x2r, yc, yr)

comparasion(cbind(yl,yu)~x1l+x1u+x2l+x2u+x3l+x3u, dataF)
```

### FOMC data
```{r}
library(tidyverse)
valid_diamonds <- diamonds %>%
filter(carat !=0, x != 0, y != 0, z != 0) %>%
drop_na() %>% mutate(logcarat = log(carat),
logx = log(x),
logy = log(y),
logz = log(z))

DiamondsUnits <- factor( paste(
valid_diamonds$cut,valid_diamonds$color,valid_diamonds$clarity, sep="-"))

DiamondsIdt <- AgrMcDt(valid_diamonds[,c("logcarat","logx","logy","logz")], agrby=DiamondsUnits)

range_list = exp(Ranges(DiamondsIdt)/2)
central_list = MidPoints(DiamondsIdt)

yc = central_list$arr_delay.MidP
yr = range_list$arr_delay.LogR
yl = yc-yr
yu = yc+yr
```

### MHRD_processed
```{r message=TRUE, warning=TRUE}
MHRD_processed = read.csv("MHRD_processed.csv", header = T)
# source("RobustRegression\\estimation of different methods.R")

dataM = data.frame(
    yl = MHRD_processed$riskLow,
    yu = MHRD_processed$riskHigh,
    x1l = MHRD_processed$DiastolicBP,
    x2l = MHRD_processed$AgeLow,
    x3l = MHRD_processed$BSLow,
    x4l = MHRD_processed$HeartRateLow,
    x1u = MHRD_processed$SystolicBP,
    x2u = MHRD_processed$AgeHigh,
    x3u = MHRD_processed$BSHigh,
    x4u = MHRD_processed$HeartRateHigh
)

# comparasion(cbind(yl,yu)~x1l+x1u+x2l+x2u+x3l+x3u+x4l+x4u, dataM)
```


```{r}
outlier_comparasion(cbind(yl,yu)~x1l+x1u+x2l+x2u+x3l+x3u+x4l+x4u, dataM,seed = 0, outlierType = 0)
```


```{r}
outlier_comparasion(cbind(yl,yu)~x1l+x1u+x2l+x2u+x3l+x3u+x4l+x4u, dataM,seed = 0, outlierType = 1,alpha = 0.15)
```

```{r}
outlier_comparasion(cbind(yl,yu)~x1l+x1u+x2l+x2u+x3l+x3u+x4l+x4u, dataM,seed = 0, outlierType = 2,alpha = 0.15)
```

```{r}
outlier_comparasion(cbind(yl,yu)~x1l+x1u+x2l+x2u+x3l+x3u+x4l+x4u, dataM,seed = 0, outlierType = 3,alpha = 0.15)
```

```{r}
outlier_comparasion(cbind(yl,yu)~x1l+x1u+x2l+x2u+x3l+x3u+x4l+x4u, dataM,seed = 0, outlierType = 4,alpha = 0.15)
```

### outlier comparasion with fixed alpha= 0.1
```{r}
outlier_comparasion_simu(cbind(yl,yu)~xl+xu, n=500, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType = 1, niter=1000)
```

```{r}
outlier_comparasion_simu(cbind(yl,yu)~xl+xu, n=500, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType = 2, niter=1000)
```

```{r}
outlier_comparasion_simu(cbind(yl,yu)~xl+xu, n=500, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType = 3, niter=1000)
```

```{r}
outlier_comparasion_simu(cbind(yl,yu)~xl+xu, n=500, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType = 4, niter=1000)
```

```{r}
outlier_comparasion_simu(cbind(yl,yu)~xl+xu, n=500, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType = 0, niter=1000)
```

```{r}
outlier_comparasion_simu(cbind(yl,yu)~xl+xu, n=500, 0, 20, 0, 2, 0, 5, 0.2, 0.5, 0, 5,-10,-5, seed=0, outlierType = 5, niter=1000)
```

